name: Keep Streamlit Dashboard Awake

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Dashboard
        run: |
          curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://nse-sql-analytics-140423102005.streamlit.app/" -o /dev/null || true